### ISSUE TITLE
Protect RecyclerCollectionDataAdapter against Collection with a null value.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1199]
App: Toggl Time Tracker - 8.1.1 (65) #2
    **Stack Trace**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Toggl.Joey.UI.Adapters.RecyclerCollectionDataAdapter`1[T].get_ItemCount () &lt;0x9cd50020 + 0x00030&gt; in &lt;filename unknown&gt;:0 
  at Android.Support.V7.Widget.RecyclerView+Adapter.n_GetItemCount (IntPtr jnienv, IntPtr native__this) &lt;0x9cd4ff60 + 0x00037&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:9f844de7-d16f-4ecd-b75f-c3882242b6cf (intptr,intptr)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x94407c90 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod) &lt;0xb3e19d80 + 0x000db&gt; in &lt;filename unknown&gt;:0 
  at Android.App.Activity.OnDestroy () &lt;0x943e2008 + 0x00103&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Joey.UI.Activities.BaseActivity.OnDestroy () &lt;0x943e1ed8 + 0x0000f&gt; in &lt;filename unknown&gt;:0 
  at Android.App.Activity.n_OnDestroy (IntPtr jnienv, IntPtr native__this) &lt;0x943e1e88 + 0x00037&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:693aed80-187e-4db6-80eb-8efdd625a780 (intptr,intptr)
	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.n_onDestroy(Native Method)
	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.onDestroy(BaseActivity.java:46)
	at android.app.Activity.performDestroy(Activity.java:6422)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3846)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3877)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	... 3 more

```
TestFairy session: [67](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2621755/sessions/67)
Date: 2016-01-26 06:02:34
User: User-1
Device: Sony - D6603  - 6.0.1 API 23

**Comment by monday8am** [comment]
closed by 7a017f5032e1cec125fec41171d1056b5418c427
