### ISSUE TITLE
Review LoadMore method inside TimeEntryFeed and "ToListAsync"

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1225]
App: Toggl Time Tracker - 8.1.1 (65) #1
    **Stack Trace**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Toggl.Phoebe.Data.Utils.TimeEntriesFeed+&lt;LoadMore&gt;c__async0+&lt;LoadMore&gt;c__AnonStorey5.&lt;&gt;m__0 (Toggl.Phoebe.Data.DataObjects.TimeEntryData entry) &lt;0x9a891f20 + 0x00078&gt; in &lt;filename unknown&gt;:0 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1 action) &lt;0x9a891cd0 + 0x0007b&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Phoebe.Data.Utils.TimeEntriesFeed+&lt;LoadMore&gt;c__async0.MoveNext () &lt;0x9b087000 + 0x00a53&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x9a894d30 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) &lt;0x9a894390 + 0x000bb&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) &lt;0x9a894298 + 0x0008b&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) &lt;0x9e99f3e8 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () &lt;0x9a89de88 + 0x0001b&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Phoebe.Data.ViewModels.LogTimeEntriesViewModel+&lt;LoadMore&gt;c__async0.MoveNext () &lt;0x9b0a6a28 + 0x00157&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x9a894d30 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) &lt;0x9a894390 + 0x000bb&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) &lt;0x9a894298 + 0x0008b&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) &lt;0x9e99f3e8 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () &lt;0x9e99fa98 + 0x00017&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Joey.UI.Fragments.LogTimeEntriesListFragment+&lt;OnViewCreated&gt;c__async0.MoveNext () &lt;0x9b550730 + 0x00833&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x9a894d30 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;ThrowAsync&gt;m__0 (System.Object state) &lt;0x9a896070 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at Android.App.SyncContext+&lt;Post&gt;c__AnonStorey0.&lt;&gt;m__0 () &lt;0x9e995ba0 + 0x00027&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.Thread+RunnableImplementor.Run () &lt;0x9e995a80 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) &lt;0x9e9959d8 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:42e20114-7b2d-444a-92d2-aff53e8f121e (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	... 3 more

```
TestFairy session: [40](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2613087/sessions/40)
Date: 2016-02-05 10:39:02
User: aaron@utilizeit.com
Device: LGE - Nexus 5  - 6.0.1 API 23

**Comment by monday8am** [comment]
out of date.
