### ISSUE TITLE
Review GetProjectDataAsync inside TimeEntryModel methods.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1263]
App: Toggl Time Tracker - 8.1.1 (65) #4
    **Stack Trace**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	... 2 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) &lt;0x68108118 + 0x0015c&gt; in &lt;filename unknown&gt;:0 
  at SQLite.Net.TableQuery`1[T].First () &lt;0x65e2a1b8 + 0x0004f&gt; in &lt;filename unknown&gt;:0 
  at SQLite.Net.Async.AsyncTableQuery`1+&lt;&gt;c__DisplayClass14_0[T].&lt;FirstAsync&gt;b__0 () &lt;0x65e2a028 + 0x000ab&gt; in &lt;filename unknown&gt;:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () &lt;0x65111e78 + 0x00053&gt; in &lt;filename unknown&gt;:0 
  at System.Threading.Tasks.Task.Execute () &lt;0x651119a0 + 0x0004f&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x6796c980 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) &lt;0x6796c5c0 + 0x000bb&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) &lt;0x6796c4e0 + 0x0008b&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) &lt;0x6586db58 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () &lt;0x6586da98 + 0x0001b&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Phoebe.Data.Models.TimeEntryModel+&lt;GetProjectDataAsync&gt;c__asyncA.MoveNext () &lt;0x68667fb8 + 0x0037f&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x6796c980 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) &lt;0x6796c5c0 + 0x000bb&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) &lt;0x6796c4e0 + 0x0008b&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) &lt;0x6586db58 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () &lt;0x6586da98 + 0x0001b&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Phoebe.Data.ViewModels.LogTimeEntriesViewModel+&lt;UpdateView&gt;c__AnonStorey5+&lt;UpdateView&gt;c__async4.MoveNext () &lt;0x680acd98 + 0x002bf&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x6796c980 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;ThrowAsync&gt;m__0 (System.Object state) &lt;0x6796d108 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at Android.App.SyncContext+&lt;Post&gt;c__AnonStorey0.&lt;&gt;m__0 () &lt;0x67c93ad0 + 0x00027&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.Thread+RunnableImplementor.Run () &lt;0x681023f8 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) &lt;0x68102350 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:86912aa3-33ce-457e-9669-ee586fe1eafa (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	... 5 more

```
TestFairy session: [8](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2790308/sessions/8)
Date: 2016-02-12 00:23:26
User: kyllike.kimmel@gmail.com
Device: Samsung - Galaxy S4 mini (GT-I9195) - 4.4.2 API 19

**Comment by monday8am** [comment]
out of date. not present in the new architecture.
