### ISSUE TITLE
Review TimeEntryModel method: GetWorkspaceDataAsync

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1274]
App: Toggl Time Tracker - 8.1.1 (65) #4
    **Stack Trace**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) &lt;0x9b805508 + 0x0015c&gt; in &lt;filename unknown&gt;:0 
  at SQLite.Net.TableQuery`1[T].First () &lt;0x9980d6d0 + 0x0004f&gt; in &lt;filename unknown&gt;:0 
  at SQLite.Net.Async.AsyncTableQuery`1+&lt;&gt;c__DisplayClass14_0[T].&lt;FirstAsync&gt;b__0 () &lt;0x9980d540 + 0x000ab&gt; in &lt;filename unknown&gt;:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () &lt;0xaf865e00 + 0x00053&gt; in &lt;filename unknown&gt;:0 
  at System.Threading.Tasks.Task.Execute () &lt;0xaf865c38 + 0x0004f&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x8d4367f8 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) &lt;0x8d436438 + 0x000bb&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) &lt;0x8d436358 + 0x0008b&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) &lt;0xaf857650 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () &lt;0xaf857590 + 0x0001b&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Phoebe.Data.Models.TimeEntryModel+&lt;GetWorkspaceDataAsync&gt;c__asyncD.MoveNext () &lt;0x90d55ae8 + 0x0037f&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x8d4367f8 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) &lt;0x8d436438 + 0x000bb&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) &lt;0x8d436358 + 0x0008b&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) &lt;0xaf857650 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () &lt;0xaf857590 + 0x0001b&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Phoebe.Data.ViewModels.EditTimeEntryViewModel+&lt;UpdateRelationships&gt;c__AnonStorey9+&lt;UpdateRelationships&gt;c__async8.MoveNext () &lt;0x90d532b8 + 0x00257&gt; in &lt;filename unknown&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x8d4367f8 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;ThrowAsync&gt;m__0 (System.Object state) &lt;0x8d43af58 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at Android.App.SyncContext+&lt;Post&gt;c__AnonStorey0.&lt;&gt;m__0 () &lt;0xaf83f568 + 0x00027&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.Thread+RunnableImplementor.Run () &lt;0xaf83eef0 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) &lt;0xaf83ee48 + 0x0003f&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:9577d4b7-03f5-4093-92e6-9def5d613c49 (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5290)
	... 4 more

```
TestFairy session: [19](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2790308/sessions/19)
Date: 2016-02-15 08:03:52
User: User-13
Device: LGE - LG-D850  - 5.0.1 API 21

**Comment by monday8am** [comment]
out of date. not present in the new architecture.
