### ISSUE TITLE
Evaluate fragment navigation to avoid ViewModel nullification. 

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1283]
App: Toggl Time Tracker - 8.1.1 (65) #3
    **Stack Trace**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
	... 2 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Toggl.Joey.UI.Fragments.EditTimeEntryFragment.OnDestroyView () &lt;0x67e875f0 + 0x00018&gt; in &lt;filename unknown&gt;:0 
  at Android.Support.V4.App.Fragment.n_OnDestroyView (IntPtr jnienv, IntPtr native__this) &lt;0x67e875a0 + 0x00037&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:c43cba67-04d9-431c-85a9-37a844be7ef0 (intptr,intptr)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () &lt;0x673bd8d8 + 0x00024&gt; in &lt;filename unknown&gt;:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod) &lt;0x632783d0 + 0x000db&gt; in &lt;filename unknown&gt;:0 
  at Android.App.Activity.OnDestroy () &lt;0x6681fdc0 + 0x00103&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Joey.UI.Activities.BaseActivity.OnDestroy () &lt;0x6681fc78 + 0x0000f&gt; in &lt;filename unknown&gt;:0 
  at Android.App.Activity.n_OnDestroy (IntPtr jnienv, IntPtr native__this) &lt;0x6681fc28 + 0x00037&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:8d9cfd84-e230-4838-8b95-537c6f757cae (intptr,intptr)
	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.n_onDestroy(Native Method)
	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.onDestroy(BaseActivity.java:46)
	at android.app.Activity.performDestroy(Activity.java:5452)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1119)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3681)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3712)
	at android.app.ActivityThread.access$1400(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5315)
	... 5 more

```
TestFairy session: [33](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2767366/sessions/33)
Date: 2016-02-16 02:39:09
User: User-12
Device: Xiaomi - 2013023  - 4.4.2 API 19

**Comment by monday8am** [comment]
duplicated by #1348
