### ISSUE TITLE
Out of memory bug.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1345]
App: Toggl Time Tracker - 8.1.1 (65) #9
    **Stack Trace**
```
java.lang.OutOfMemoryError: Failed to allocate a 12257292 byte allocation with 9485096 free bytes and 9MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2635)
	at android.content.res.Resources.loadDrawable(Resources.java:2540)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
	at android.widget.ImageView.&lt;init&gt;(ImageView.java:152)
	at android.widget.ImageView.&lt;init&gt;(ImageView.java:140)
	at android.support.v7.widget.AppCompatImageView.&lt;init&gt;(AppCompatImageView.java:58)
	at android.support.v7.widget.AppCompatImageView.&lt;init&gt;(AppCompatImageView.java:54)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:95)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:938)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:992)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at md5541ebcfeb48f0c16e27077d4b1acb662.LogTimeEntriesListFragment.n_onCreateView(Native Method)
	at md5541ebcfeb48f0c16e27077d4b1acb662.LogTimeEntriesListFragment.onCreateView(LogTimeEntriesListFragment.java:34)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```
TestFairy session: [1](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2956110/sessions/1)
Date: 2016-03-06 13:27:33
User: User-57
Device: LGE - Nexus 5  - 6.0.1 API 23

**Comment by monday8am** [comment]
out of date.
