### ISSUE TITLE
Null object at EditTimeEntryFragment OnDestroyView

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1354]
App: Toggl Time Tracker - 8.1.2 (66) #2
    **Stack Trace**
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	... 2 more
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Toggl.Joey.UI.Fragments.EditTimeEntryFragment.OnDestroyView () [0x00006] in &lt;filename unknown&gt;:0 
  at Android.Support.V4.App.Fragment.n_OnDestroyView (IntPtr jnienv, IntPtr native__this) [0x00009] in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:b5d420ff-50a3-4b8a-a48b-1dd42f7af3aa (intptr,intptr)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in &lt;filename unknown&gt;:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (JniObjectReference instance, JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in &lt;filename unknown&gt;:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00066] in &lt;filename unknown&gt;:0 
  at Android.App.Activity.OnDestroy () [0x0000a] in &lt;filename unknown&gt;:0 
  at Toggl.Joey.UI.Activities.BaseActivity.OnDestroy () [0x00000] in &lt;filename unknown&gt;:0 
  at Android.App.Activity.n_OnDestroy (IntPtr jnienv, IntPtr native__this) [0x00009] in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:c3bac02e-7c9f-4439-81e0-d87c03e9ad25 (intptr,intptr)
	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.n_onDestroy(Native Method)
	at md5d0def3047409cb8594a2ecbf8acf6aee.BaseActivity.onDestroy(BaseActivity.java:47)
	at android.app.Activity.performDestroy(Activity.java:5630)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1123)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3799)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3830)
	at android.app.ActivityThread.access$1500(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	... 5 more

```
TestFairy session: [11](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2968644/sessions/11)
Date: 2016-03-08 08:22:49
User: User-79
Device: Samsung - Galaxy S4 mini (GT-I9195) - 4.4.2 API 19

**Comment by monday8am** [comment]
out of date. fixed in new releases.
