### ISSUE TITLE
java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1365]
App: Toggl Time Tracker - 8.1.2 (66) #3
    **Stack Trace**
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:831)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:449)
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:388)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:187)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:142)
	at java.util.Arrays.sort(Arrays.java:1970)
	at java.util.Collections.sort(Collections.java:1864)
	at android.view.ViewGroup$ChildListForAccessibility.init(ViewGroup.java:6621)
	at android.view.ViewGroup$ChildListForAccessibility.obtain(ViewGroup.java:6586)
	at android.view.ViewGroup.addChildrenForAccessibility(ViewGroup.java:1689)
	at android.view.ViewGroup.addChildrenForAccessibility(ViewGroup.java:1698)
	at android.view.ViewGroup.addChildrenForAccessibility(ViewGroup.java:1698)
	at android.view.ViewGroup.addChildrenForAccessibility(ViewGroup.java:1698)
	at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:2515)
	at android.view.View$AccessibilityDelegate.onInitializeAccessibilityNodeInfo(View.java:19405)
	at android.support.v4.view.AccessibilityDelegateCompatIcs.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatIcs.java:96)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:185)
	at android.support.v4.view.AccessibilityDelegateCompat.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:438)
	at android.support.v4.view.ViewPager$MyAccessibilityDelegate.onInitializeAccessibilityNodeInfo(ViewPager.java:2869)
	at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:233)
	at android.support.v4.view.AccessibilityDelegateCompatJellyBean$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompatJellyBean.java:61)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:5193)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:5156)
	at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:19474)
	at android.view.View.createAccessibilityNodeInfo(View.java:5141)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchPredecessorsOfRealNode(AccessibilityInteractionController.java:746)
	at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:714)
	at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:147)
	at android.view.AccessibilityInteractionController.access$300(AccessibilityInteractionController.java:49)
	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:971)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5072)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)

```
TestFairy session: [14](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/2969176/sessions/14)
Date: 2016-03-09 07:35:03
User: User-82
Device: Xiaomi - MI 4LTE  - 4.4.4 API 19

**Comment by monday8am** [comment]
duplicated
