### ISSUE TITLE
Error when logging in or signing up with email in unidirectional Android

### ISSUE THREAD

**Issue by alfonsogarciacaro** [toggl/mobile#1517]
When trying to log in or sign up with an email in unidirectional Android the following error is thrown:

```
[SyncManager] Signing up with email (c@c.es).
[SyncManager] Failed to authenticate user. Unknown error.
[SyncManager] javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[SyncManager] 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)
[SyncManager] 	at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
[SyncManager] 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
[SyncManager] 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:433)
[SyncManager] 	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
[SyncManager] 	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
[SyncManager] 	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
[SyncManager] 	at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
[SyncManager] 	at dalvik.system.NativeStart.run(Native Method)
[SyncManager] Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[SyncManager] 	at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:192)
[SyncManager] 	at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:163)
[SyncManager] 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:597)
[SyncManager] 	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
[SyncManager] 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
[SyncManager] 	... 8 more
[SyncManager] Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[SyncManager] 	... 13 more
```

This seems to be related to the fact that the staging server is using an invalid certificate for secure connections. We must find a workaround for this for debugging.

Android OS: Jelly Bean (API 16)

**Comment by monday8am** [comment]
@alfonsogarciacaro I'm suffering the same, not @taavirehemagi.

**Comment by alfonsogarciacaro** [comment]
I've changed to production URL to avoid this problem. Now login works but when I try to update a time entry I get the following error:

```
[SyncManager] Failed to sync
[SyncManager] java.io.IOException: unexpected end of stream
[SyncManager] 	at libcore.net.http.FixedLengthOutputStream.close(FixedLengthOutputStream.java:58)
[SyncManager] 	at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:804)
[SyncManager] 	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
[SyncManager] 	at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
[SyncManager] 	at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
[SyncManager] 	at dalvik.system.NativeStart.run(Native Method)
```

**Comment by alfonsogarciacaro** [comment]
Seems the problem can be solved (for the production server) using the ModernHttpClient component:
https://components.xamarin.com/view/modernhttpclient

**Comment by alfonsogarciacaro** [comment]
The login issue in Debug mode is solved by installing Toggl CA in the device.
