### ISSUE TITLE
android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#1682]
App: Toggl Time Tracker - 8.1.3 (67) #7
    **Stack Trace**
```
android.view.InflateException: Binary XML file line #1: Error inflating class &lt;unknown&gt;
	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at md585382da9cec5dcdd708c8560391f0206.RecyclerCollectionDataAdapter_1.n_onCreateViewHolder(Native Method)
	at md585382da9cec5dcdd708c8560391f0206.RecyclerCollectionDataAdapter_1.onCreateViewHolder(RecyclerCollectionDataAdapter_1.java:32)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5228)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:761)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14075)
	at android.view.ViewGroup.layout(ViewGroup.java:4657)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2010)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1831)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1120)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4585)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:525)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4953)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
	... 81 more
Caused by: android.runtime.JavaProxyThrowable: System.NotSupportedException: Could not activate JNI Handle 0x4e10002d (key_handle 0x42020ba8) of Java type 'md5a9517e52bde86251e07995553e87b6c1/NotificationImageView' as managed type 'Toggl.Joey.UI.Views.NotificationImageView'. ---&gt; System.InvalidCastException: Specified cast is not valid.
  at Java.Lang.Object.ShouldReplaceMapping (System.WeakReference current, IntPtr handle) &lt;0x63056aa0 + 0x0009c&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.Object._RegisterInstance (IJavaObject instance, IntPtr key, IntPtr handle) &lt;0x60ec72b0 + 0x00167&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.Object.RegisterInstance (IJavaObject instance, IntPtr value, JniHandleOwnership transfer, System.IntPtr&amp; handle) &lt;0x60ec6b28 + 0x0021f&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.Object.SetHandle (IntPtr value, JniHandleOwnership transfer) &lt;0x60ec6aa8 + 0x0002f&gt; in &lt;filename unknown&gt;:0 
  at Java.Lang.Object..ctor (IntPtr handle, JniHandleOwnership transfer) &lt;0x60ec6a10 + 0x0005b&gt; in &lt;filename unknown&gt;:0 
  at Android.Views.View..ctor (IntPtr javaReference, JniHandleOwnership transfer) &lt;0x6271b300 + 0x00023&gt; in &lt;filename unknown&gt;:0 
  at Android.Widget.ImageView..ctor (Android.Content.Context context, IAttributeSet attrs) &lt;0x6271c4f0 + 0x00037&gt; in &lt;filename unknown&gt;:0 
  at Toggl.Joey.UI.Views.NotificationImageView..ctor (Android.Content.Context context, IAttributeSet attrs) &lt;0x64983f08 + 0x0004f&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:1bc76e53-e3f9-439e-b25d-bbda3f4085b5 (intptr,object[])
  at Java.Interop.TypeManager.n_Activate (IntPtr jnienv, IntPtr jclass, IntPtr typename_ptr, IntPtr signature_ptr, IntPtr jobject, IntPtr parameters_ptr) &lt;0x61100590 + 0x002ef&gt; in &lt;filename unknown&gt;:0 
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.n_Activate (IntPtr jnienv, IntPtr jclass, IntPtr typename_ptr, IntPtr signature_ptr, IntPtr jobject, IntPtr parameters_ptr) &lt;0x61100590 + 0x00504&gt; in &lt;filename unknown&gt;:0 
  at (wrapper dynamic-method) System.Object:35428118-e2e5-4ff0-9511-7e1b673694a4 (intptr,intptr,intptr,intptr,intptr,intptr)
	at mono.android.TypeManager.n_activate(Native Method)
	at mono.android.TypeManager.Activate(TypeManager.java:7)
	at md5a9517e52bde86251e07995553e87b6c1.NotificationImageView.&lt;init&gt;(NotificationImageView.java:31)
	... 84 more

```
TestFairy session: [543](https://toggl.testfairy.com/projects/1985413-toggltimetracker/builds/3313893/sessions/543)
Date: 2016-06-14 06:55:20
User: User-150
Device: Samsung - Galaxy Tab 2 (SCH-i705) - 4.1.2 API 16

**Comment by monday8am** [comment]
out of date.
