### ISSUE TITLE
The start button doesn't seem to work

### ISSUE THREAD

**Issue by gabor-farkas** [toggl/mobile#862]
Hi, the top-right start button is now properly displayed, but doesn't seem to work. I can start new entries by pressing the 'play' icon on a previous entry in the log list and then change its properties. The stop button works as expected.
Shall I include a video?
LG-D855, Android 5.0, Toggl 8.0.4

**Comment by monday8am** [comment]
Hi @gabor-farkas, it works ok in our simulator / devices. The button is the same for different actions, so, if the clickable area works for one action (stop) should works in the same way for other action  like start. In other words, probably it is a different bug. 

We'll wait a bit for more reports from users (I'll keep the issue open). Thanks again for your feedback!

**Comment by gabor-farkas** [comment]
I managed to fetch some logs :)
```
W/TimerComponent(27100): Failed to change time entry state.
W/TimerComponent(27100): md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.InvalidOperationException: Cannot start tracking time entry with start/stop time set already
.
W/TimerComponent(27100):   at Toggl.Phoebe.Data.Models.TimeEntryModel+<StartAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0
W/TimerComponent(27100): --- End of stack trace from previous location where exception was thrown ---
W/TimerComponent(27100):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
W/TimerComponent(27100):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
W/TimerComponent(27100):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
:0
W/TimerComponent(27100):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0
W/TimerComponent(27100):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0
W/TimerComponent(27100):   at Toggl.Joey.UI.Components.TimerComponent+<OnActionButtonClicked>c__async0.MoveNext () [0x00000] in <filename unknown>:0
W/TimerComponent(27100):        at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
W/TimerComponent(27100):        at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:29)
W/TimerComponent(27100):        at android.view.View.performClick(View.java:4763)
W/TimerComponent(27100):        at android.view.View$PerformClick.run(View.java:19821)
W/TimerComponent(27100):        at android.os.Handler.handleCallback(Handler.java:739)
W/TimerComponent(27100):        at android.os.Handler.dispatchMessage(Handler.java:95)
W/TimerComponent(27100):        at android.os.Looper.loop(Looper.java:135)
W/TimerComponent(27100):        at android.app.ActivityThread.main(ActivityThread.java:5274)
W/TimerComponent(27100):        at java.lang.reflect.Method.invoke(Native Method)
W/TimerComponent(27100):        at java.lang.reflect.Method.invoke(Method.java:372)
W/TimerComponent(27100):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
W/TimerComponent(27100):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```

I tried a force restart on the app, but that didn't help.

**Comment by monday8am** [comment]
ahh, great feedback! We have references about this bug. The incidence is small but maybe could increase. 
XI: 033473e64c38b2b2fd2eb0f3286c032f19a52bf4 (internal code)

I have tried a bit but I can't simulate it. @gabor-farkas  Are you suffering it right now? . If is possible, do a logout - login and let me know if is fixed.

**Comment by gabor-farkas** [comment]
Yup, login-logout helped!
I'll try to spot a reproduction next time it occurs.

**Comment by monday8am** [comment]
Seems to be some action (that we have to discover) corrupt the state of the running entry. This running entry is affected by the start / stop button. A logout - login make a fresh copy of your data from the server. Im happy that the workaround worked. I'll try to fix the bug this week.

thanks for your help!
