### ISSUE TITLE
Error processing a GCM message.

### ISSUE THREAD

**Issue by monday8am** [toggl/mobile#926]
[GcmService] Failed to process pushed message.
[GcmService] md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.FormatException: Input string was not in a correct format.
[GcmService]    at System.Number.StringToNumber (System.String str, NumberStyles options, System.NumberBuffer& number, System.Globalization.NumberFormatInfo info, Boolean parseDecimal) in <filename unknown>:line 0
[GcmService]    at System.Number.ParseInt64 (System.String value, NumberStyles options, System.Globalization.NumberFormatInfo numfmt) in <filename unknown>:line 0
[GcmService]    at System.Int64.Parse (System.String s, IFormatProvider provider) in <filename unknown>:line 0
[GcmService]    at System.Convert.ToInt64 (System.String value) in <filename unknown>:line 0
[GcmService]    at Toggl.Joey.Net.GcmService+<OnStart>c__async0.MoveNext () in <filename unknown>:line 0
[GcmService] 	at md52c30aed6290f57162f48dd9e88c62476.GcmService.n_onStartCommand(Native Method)
[GcmService] 	at md52c30aed6290f57162f48dd9e88c62476.GcmService.onStartCommand(GcmService.java:40)
[GcmService] 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2726)
[GcmService] 	at android.app.ActivityThread.access$2100(ActivityThread.java:144)
[GcmService] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
[GcmService] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[GcmService] 	at android.os.Looper.loop(Looper.java:136)
[GcmService] 	at android.app.ActivityThread.main(ActivityThread.java:5146)
[GcmService] 	at java.lang.reflect.Method.invokeNative(Native Method)
[GcmService] 	at java.lang.reflect.Method.invoke(Method.java:515)
[GcmService] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
[GcmService] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
[GcmService] 	at dalvik.system.NativeStart.main(Native Method)
[Timeline] Timeline: Activity_launch_request id:com.toggl.timer time:809046

**Comment by monday8am** [comment]
not present in Xamarin Insights. Closed for the moment.
